### ISSUE TITLE
ImportError: No module named 'rdflib.plugins.parsers.pyRdfa'

### ISSUE THREAD

**Issue by svnshikhil** [scrapinghub/extruct#135]
This issue occurs when we install warcio package

from rdflib.plugins.parsers.pyRdfa import pyRdfa as PyRdfa, Options, logger as pyrdfa_logger
ImportError: No module named 'rdflib.plugins.parsers.pyRdfa'

**Comment by lopuhin** [comment]
@svnshikhil this should be fixed in the lateest release, 0.9.0, could you please check it?

**Comment by saggu** [comment]
@lopuhin there seems to be a version conflict re:rdflib

`ERROR: extruct 0.9.0 has requirement rdflib<5.0.0, but you'll have rdflib 5.0.0 which is incompatible.`

Will this be fixed?

**Comment by Gallaecio** [comment]
Do you need rdflib 5.0.0?

**Comment by saggu** [comment]
I don't but we are using other libraries as `SPARQLWRAPPER` which is using the latest rdflib.
For future proofing we use the latest version of libraries anyway.

**Comment by lopuhin** [comment]
@saggu I see, unfortunately ``extruct`` is not compatible with latest rdflib 5.0.0, we put a restriction on the version in 0.9.0 but you are right that this is not a viable solution long term, let's use this issue to track this.

I think the plan to improve this could be:
1. at least don't fail to import with latest rdflib, so that we loos only extractions provided by it
2. move off rdflib, either to another lib or adding our implementation, potentially derived from rdflib

**Comment by svnshikhil** [comment]
> @svnshikhil this should be fixed in the lateest release, 0.9.0, could you please check it?

Yeah, it's working 

Thank you all

**Comment by lopuhin** [comment]
Re-opening because the proper fix is still not in place, we want to allow users of extruct to use the latest rdflib, see https://github.com/scrapinghub/extruct/issues/135#issuecomment-619824716

**Comment by lopuhin** [comment]
This is fixed by #161 and released in v0.12.0
