### ISSUE TITLE
support pre-parsed lxml.etree and faster json

### ISSUE THREAD

**Issue by codinguncut** [scrapinghub/extruct#37]
please add functions to provide a pre-parsed lxml.etree instead of htmlstring.
Also, using a library such as "ujson" may significantly speedup processing for jsonld.

**Comment by redapple** [comment]
@codinguncut ,
Although it's not documented (nor explicitly tested), 2 of the extractors already support passing an lxml document directly (e.g. result of an lxml parser's `.fromstring()`, which is how it's implemented for `.extract()`):
* [`extruct.jsonld.JsonLdExtractor.extract_items(document)`](https://github.com/scrapinghub/extruct/blob/5f58236024530004f5cb824444aa04ef6f9db19f/extruct/jsonld.py#L20)
* [`w3cmicrodata.LxmlMicrodataExtractor.extract_items(document, url)`](https://github.com/scrapinghub/extruct/blob/5f58236024530004f5cb824444aa04ef6f9db19f/extruct/w3cmicrodata.py#L47)

The RDFa extractor is a bit different since rdflib is tricked into thinking it is handling an `xml.dom` tree, but the lxml parser is available: [`extruct.rdfa.XmlDomHTMLParser`](https://github.com/scrapinghub/extruct/blob/b9dc15c23bc81bb7cda24b4095d2cab9682a0f75/extruct/rdfa.py#L170) and a method can be added to pass an `xml.dom` compatible tree.

Regarding speeding up JSON parsing, is `usjon` the best option these day? (honest question, I haven't used it in a long time)

**Comment by codinguncut** [comment]
Hi,
thank you for sharing this (undocumented) functionality.

I'm not sure if `ujson` is the "best" option (whatever that means), but it's significantly faster than vanilla `json` (especially on py2) and I've been using it as a robust drop-in replacement.

http://artem.krylysov.com/blog/2015/09/29/benchmark-python-json-libraries/

**Comment by redapple** [comment]
I meant "best" as "fastest" as this is one of your points.
PRs for trying ujson if available and documentation of extractors methods are welcome.

**Comment by redapple** [comment]
`extract_items(document, url, *args, **kwargs)` methods have been added to all extractors, taking an lxml-parsed document as input.
I've moved the usjon feature request to another issue #49
